#ifndef REPORTES_H_INCLUDED
#define REPORTES_H_INCLUDED

void ventaxVendedor(); //VENTAS DE UN VENDEDOR ESPECIFICO (DE QUE PERIODO)
void ventaxMes(); //VENTAS TOTALES POR MES
void ventaxAnio(); //VENTAS TOTALES POR ANIO
void comisiones(); //VER POR ANIO Y TOTALES POR VENDEDOR DAR AMBAS OPCIONES


#endif // REPORTES_H_INCLUDED
